spring:
  application:
    name: cheburek
  
  datasource:
    url: jdbc:postgresql://localhost:5432/habrdb
    username: habrpguser
    password: pgpwd4habr
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

jwt:
  secret: 8j1LcKstsPMhshhzFGsccy+DGMudYM8d2BB4P4VEMPVhXKx5ebK/S0bSihNAgSk/BayKLOM77lTeiVKqOBeB3w==
  expiration: 604800000

telegram:
  bot:
    token: 8543724938:AAFZjNZBkx67m97I_bZ971FIID9Xu5diK7Y

server:
  port: 8080
  address: localhost
